// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type GameState struct {
	ID          int64
	CurrentWeek sql.NullInt64
	SeasonID    int64
}

type Match struct {
	ID       int64
	SeasonID int64
	HomeID   int64
	GuestID  int64
	Played   sql.NullBool
	Week     int64
}

type MatchResult struct {
	ID         int64
	MatchID    int64
	HomeScore  int64
	GuestScore int64
	WinnerID   sql.NullInt64
}

type Season struct {
	ID         int64
	Year       int64
	IsCurrent  sql.NullBool
	IsComplete sql.NullBool
}

type Standing struct {
	ID       int64
	TeamID   int64
	SeasonID int64
	Points   sql.NullInt64
	Wins     sql.NullInt64
	Draws    sql.NullInt64
	Losses   sql.NullInt64
	GoalDiff sql.NullInt64
}

type Team struct {
	ID       int64
	Name     string
	Strength sql.NullInt64
	Budget   sql.NullInt64
}

type Teamstat struct {
	ID                 int64
	Team               interface{}
	Value              sql.NullInt64
	Lastseasonstanding sql.NullInt64
}
