// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Match struct {
	ID     int64
	Home   interface{}
	Guest  interface{}
	Played sql.NullBool
	Week   sql.NullInt64
}

type MatchResult struct {
	ID     int64
	Match  interface{}
	Winner interface{}
}

type Season struct {
	ID        int64
	Name      string
	Standings interface{}
}

type Standing struct {
	ID       int64
	Points   sql.NullInt64
	Wins     sql.NullInt64
	Draws    sql.NullInt64
	Losses   sql.NullInt64
	GoalDiff sql.NullInt64
}

type Team struct {
	ID       int64
	Name     string
	Strength sql.NullInt64
}

type Teamstanding struct {
	ID       int64
	Team     interface{}
	Standing interface{}
}

type Teamstat struct {
	ID                 int64
	Team               interface{}
	Value              sql.NullInt64
	Lastseasonstanding sql.NullInt64
}
