root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["echo 'hello air'", "mkdir -p tmp", "mkdir -p bin"]

cmd = "~/go/bin/templ generate && go build -o ./bin/main main.go"

post_cmd = ["echo 'bye air'"]

bin = "bin/main"

# full_bin = "APP_ENV=dev APP_USER=air ./bin/main"
# args_bin = ["hello", "world"]

include_ext = ["go", "tpl", "tmpl", "templ", "html"]

exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]

include_dir = []
include_file = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true

log = "air.log"
poll = false
poll_interval = 500 # ms
delay = 0 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # nanosecond
rerun = false
rerun_delay = 500

[log]
time = false
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = true
proxy_port = 8090
app_port = 8080
